# Sandy sandbox test configuration
# Used by: sandy.exe -c test_sandy_config.toml -x Python\python.exe test_sandy.py

[read]
"C:\Users\H\AppData\Local\Programs\Python\Python314"
"C:\Users\H\test_R"
"C:\repos\sandy\"

[write]
"C:\Users\H\test_W"

[readwrite]
"C:\Users\H\test_RW"
